import Head from "next/head";
import styled from "@emotion/styled";
import { Container } from "../components/Container";
import { Navigation } from "../components/Navigation";
import { Main } from "../components/Main";
import { Conceito } from "../components/Conceito";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Eureka TV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Lato&family=Open+Sans&display=swap"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css"
        />
      </Head>
      <header>
        <HeaderContent>
          <img src="./logo-eureka.png" alt="logo" />
        </HeaderContent>
      </header>

      <main>
        <section id="home">
          <Container style={{ minHeight: "calc(100vh - 154px)" }}>
            <Navigation />
            <Main />
          </Container>
        </section>
        <section id="#conceito">
          <Conceito />
        </section>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}

const HeaderContent = styled(Container)({
  margin: "10px auto 14px",
});
